// SPDX-License-Identifier: AGPL-3.0-only

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Issue #299: the interactive init AI .env writer (writeOrKeepEnvFile →
// writeEnvFileContent) truncated the whole file with a single KEY line,
// silently destroying other stored secrets (e.g. a CLOUDFLARE_API_TOKEN kept
// from a previous install / written by the CDN step). These tests lock in the
// read-modify-write behavior: the managed key is upserted while every other
// line (secrets, comments, blanks) is preserved, and perms stay 0600.
//
// Per Hard Rule 3 no real-looking secret values appear here — the "other
// secret" is an obvious placeholder, never a token-shaped literal.

const otherSecretKey = "CLOUDFLARE_API_TOKEN" //nolint:gosec // G101: an env var NAME, not a credential value

// unrelatedSecretValue is a deliberately non-secret placeholder standing in for
// an operator-stored token. It must not look like a real key.
const unrelatedSecretValue = "cf-placeholder-not-a-real-token"

// TestInit_EnvWriter_PreservesUnrelatedSecrets is the direct #299 regression:
// a .env holding an unrelated secret (plus a hand-added comment) must keep that
// secret when the AI step writes the API key, and perms must stay 0600.
func TestInit_EnvWriter_PreservesUnrelatedSecrets(t *testing.T) {
	dir := t.TempDir()
	envPath := filepath.Join(dir, envFileName)

	// Pre-seed: an operator .env from a prior install — a header comment, an
	// unrelated secret, a hand-added annotation, and a blank line.
	seed := "# EzyShield environment — generated by 'ezyshield init'\n" +
		"# systemd loads this via EnvironmentFile= (see ezyshield.service).\n" +
		otherSecretKey + "=" + unrelatedSecretValue + "\n" +
		"# operator note: rotate the CF token quarterly\n" +
		"\n"
	if err := os.WriteFile(envPath, []byte(seed), 0o600); err != nil {
		t.Fatalf("pre-seed: %v", err)
	}

	// The AI step writes the Anthropic key (option-1 paste path).
	wrote, kept, err := writeOrKeepEnvFile(envPath, "ANTHROPIC_API_KEY", "test-key-placeholder")
	if err != nil {
		t.Fatalf("writeOrKeepEnvFile: %v", err)
	}
	if !wrote || kept {
		t.Fatalf("wrote=%v kept=%v, want wrote=true kept=false", wrote, kept)
	}

	data, err := os.ReadFile(envPath) //nolint:gosec // test path under t.TempDir
	if err != nil {
		t.Fatal(err)
	}
	body := string(data)

	// The unrelated secret MUST survive (this is the #299 bug).
	if !strings.Contains(body, otherSecretKey+"="+unrelatedSecretValue) {
		t.Errorf("#299: unrelated secret %s was clobbered; body=%q", otherSecretKey, body)
	}
	// The managed key MUST be present.
	if !strings.Contains(body, "ANTHROPIC_API_KEY=test-key-placeholder") {
		t.Errorf("managed key not written; body=%q", body)
	}
	// The operator's hand-added comment MUST survive.
	if !strings.Contains(body, "operator note: rotate the CF token quarterly") {
		t.Errorf("operator comment was lost; body=%q", body)
	}
	// Header must not be duplicated on the merge (renderEnvFile guard).
	if n := strings.Count(body, "generated by 'ezyshield init'"); n != 1 {
		t.Errorf("header appears %d times, want exactly 1; body=%q", n, body)
	}

	// Perms must stay 0600 — never widened.
	info, err := os.Stat(envPath)
	if err != nil {
		t.Fatalf("stat: %v", err)
	}
	if info.Mode().Perm() != 0o600 {
		t.Errorf("perms = %04o, want 0600", info.Mode().Perm())
	}
}

// TestInit_EnvWriter_UpsertsInPlace verifies that when the managed key already
// exists, it is updated in place (single line) and sibling secrets are still
// preserved — no duplicate KEY lines, no lost neighbors.
func TestInit_EnvWriter_UpsertsInPlace(t *testing.T) {
	dir := t.TempDir()
	envPath := filepath.Join(dir, envFileName)

	seed := "ANTHROPIC_API_KEY=old-placeholder\n" +
		otherSecretKey + "=" + unrelatedSecretValue + "\n"
	if err := os.WriteFile(envPath, []byte(seed), 0o600); err != nil {
		t.Fatalf("pre-seed: %v", err)
	}

	if err := writeEnvFileContent(envPath, "ANTHROPIC_API_KEY", "new-placeholder"); err != nil {
		t.Fatalf("writeEnvFileContent: %v", err)
	}

	data, err := os.ReadFile(envPath) //nolint:gosec // test path under t.TempDir
	if err != nil {
		t.Fatal(err)
	}
	body := string(data)

	if !strings.Contains(body, "ANTHROPIC_API_KEY=new-placeholder") {
		t.Errorf("key not updated; body=%q", body)
	}
	if strings.Contains(body, "ANTHROPIC_API_KEY=old-placeholder") {
		t.Errorf("stale key value survived; body=%q", body)
	}
	if n := strings.Count(body, "ANTHROPIC_API_KEY="); n != 1 {
		t.Errorf("ANTHROPIC_API_KEY appears %d times, want exactly 1; body=%q", n, body)
	}
	if !strings.Contains(body, otherSecretKey+"="+unrelatedSecretValue) {
		t.Errorf("sibling secret lost on in-place update; body=%q", body)
	}
}

// TestInit_EnvWriter_CreatesFreshWhenAbsent verifies the create path: an absent
// file yields a fresh 0600 .env with the header and the managed key.
func TestInit_EnvWriter_CreatesFreshWhenAbsent(t *testing.T) {
	dir := t.TempDir()
	envPath := filepath.Join(dir, envFileName)

	if err := writeEnvFileContent(envPath, "ANTHROPIC_API_KEY", "fresh-placeholder"); err != nil {
		t.Fatalf("writeEnvFileContent: %v", err)
	}

	info, err := os.Stat(envPath)
	if err != nil {
		t.Fatalf("stat: %v", err)
	}
	if info.Mode().Perm() != 0o600 {
		t.Errorf("perms = %04o, want 0600", info.Mode().Perm())
	}

	data, err := os.ReadFile(envPath) //nolint:gosec // test path under t.TempDir
	if err != nil {
		t.Fatal(err)
	}
	body := string(data)
	if !strings.Contains(body, "ANTHROPIC_API_KEY=fresh-placeholder") {
		t.Errorf("managed key not written; body=%q", body)
	}
	if !strings.Contains(body, "generated by 'ezyshield init'") {
		t.Errorf("fresh file missing header; body=%q", body)
	}
	if !strings.HasSuffix(body, "\n") {
		t.Errorf("file missing trailing newline; body=%q", body)
	}
}

// TestInit_EnvWriter_PreservesCRLFAndComments verifies a CRLF-line-ended file
// (operator edited on Windows) does not lose its other keys when merged.
func TestInit_EnvWriter_PreservesCRLFAndComments(t *testing.T) {
	dir := t.TempDir()
	envPath := filepath.Join(dir, envFileName)

	// CRLF line endings on the pre-existing content.
	seed := "# hand-written config\r\n" +
		otherSecretKey + "=" + unrelatedSecretValue + "\r\n"
	if err := os.WriteFile(envPath, []byte(seed), 0o600); err != nil {
		t.Fatalf("pre-seed: %v", err)
	}

	if err := writeEnvFileContent(envPath, "ANTHROPIC_API_KEY", "crlf-placeholder"); err != nil {
		t.Fatalf("writeEnvFileContent: %v", err)
	}

	data, err := os.ReadFile(envPath) //nolint:gosec // test path under t.TempDir
	if err != nil {
		t.Fatal(err)
	}
	body := string(data)
	// The unrelated secret value survives (CR may remain on the value, so match
	// on the key=value prefix).
	if !strings.Contains(body, otherSecretKey+"="+unrelatedSecretValue) {
		t.Errorf("CRLF file: unrelated secret lost; body=%q", body)
	}
	if !strings.Contains(body, "ANTHROPIC_API_KEY=crlf-placeholder") {
		t.Errorf("managed key not written; body=%q", body)
	}
}
