package main

// The report command renders the daemon's read-only "report" verb (issue
// #54): a full per-IP abuse report — as terminal text, JSON
// (sdk.AbuseReport), or a markdown document ready to attach to an abuse@
// complaint — or, without an IP, a summary listing of recorded offenders.
//
// Security (§1 SECURITY-REVIEW): report payloads embed strings copied from
// hostile log lines (reasons, categories). Every such field goes through
// sanitizeField before it reaches the terminal, and additionally through
// mdCell before it lands inside a markdown table. JSON output is safe by
// construction (encoding/json escapes control bytes).

import (
	"context"
	"encoding/json"
	"fmt"
	"net/netip"
	"strings"
	"text/tabwriter"
	"time"

	"github.com/spf13/cobra"

	"github.com/evertramos/ezy-shield/internal/daemon"
	"github.com/evertramos/ezy-shield/pkg/sdk"
)

// Rune caps applied by sanitizeField to untrusted report fields.
const (
	reportReasonMax = 200
	reportFieldMax  = 60
	// reportLineMax caps evidence log lines. It matches the daemon's own
	// per-line byte cap, so it only bites on pathological multi-byte input.
	reportLineMax = 2048
)

func newReportCmd() *cobra.Command {
	var (
		socketPath string
		permanent  bool
		output     string
		limit      int
		noFooter   bool
		evidence   bool
	)

	cmd := &cobra.Command{
		Use:   "report [ip]",
		Short: "Generate an abuse report for an offender IP (or list offenders)",
		Long: `Generate a complete abuse report for one offender IP from the daemon's
records: identity and enrichment (country, ASN), the current ban, the full
strike history with detection verdicts, and the action trail.

With -o md the report is rendered as a markdown document you can redirect to
a file and attach when reporting the address to the operator's abuse contact:

  ` + progName + ` report 203.0.113.7 -o md > abuse-203.0.113.7.md

With --evidence the report additionally includes raw log excerpts mentioning
the address, extracted on demand from the daemon's configured log sources
(never persisted; sources that rotated away are noted honestly).

Without an IP argument the command lists every offender the daemon has on
record (--permanent narrows it to permanently banned ones).

The report is read-only and works in both enforce and dry-run modes.`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if output != "text" && output != "md" {
				return fmt.Errorf("invalid output %q; valid: text, md", output)
			}
			if jsonOutput && output == "md" {
				return fmt.Errorf("--json and -o md are mutually exclusive")
			}
			if len(args) == 0 {
				if output == "md" {
					return fmt.Errorf("markdown output (-o md) requires an IP argument")
				}
				if evidence {
					return fmt.Errorf("--evidence requires an IP argument")
				}
				return runReportList(cmd, socketPath, permanent, limit)
			}
			if permanent {
				return fmt.Errorf("--permanent filters the listing mode; drop the IP argument")
			}
			if _, err := netip.ParseAddr(args[0]); err != nil {
				return fmt.Errorf("invalid ip %q: report takes a single address, not a range", args[0])
			}
			return runReportIP(cmd, socketPath, args[0], output, limit, !noFooter, evidence)
		},
	}

	cmd.Flags().StringVar(&socketPath, "socket", daemon.DefaultSocketPath,
		"path to daemon control socket")
	cmd.Flags().BoolVar(&permanent, "permanent", false,
		"listing mode: only offenders with a permanent active ban")
	cmd.Flags().StringVarP(&output, "output", "o", "text",
		"output format: text or md (markdown abuse report)")
	cmd.Flags().IntVar(&limit, "limit", 0,
		"max strike/action rows (0 = server default)")
	cmd.Flags().BoolVar(&noFooter, "no-footer", false,
		"omit the \"Generated by EzyShield\" footer from markdown output")
	cmd.Flags().BoolVar(&evidence, "evidence", false,
		"include raw log excerpts mentioning the IP (per-IP report only)")

	return cmd
}

// ── Per-IP report ────────────────────────────────────────────────────────────

func runReportIP(cmd *cobra.Command, socketPath, ip, output string, limit int, footer, evidence bool) error {
	resp, err := daemonRPC(context.Background(), socketPath,
		daemon.SocketRequest{Verb: "report", IP: ip, Limit: limit, Evidence: evidence})
	if err != nil {
		return err
	}

	var rep sdk.AbuseReport
	if err := json.Unmarshal(resp.Data, &rep); err != nil {
		return fmt.Errorf("parse report response: %w", err)
	}

	switch {
	case jsonOutput:
		return writeJSON(cmd.OutOrStdout(), rep)
	case output == "md":
		_, err := fmt.Fprint(cmd.OutOrStdout(), renderReportMarkdown(rep, footer))
		return err
	default:
		return printReportText(cmd, rep)
	}
}

// printReportText renders the report for a terminal, one section per data
// block, following the shared styler visual language.
func printReportText(cmd *cobra.Command, rep sdk.AbuseReport) error {
	w := cmd.OutOrStdout()
	s := newStyler(w)

	fmt.Fprintln(w, s.header("Abuse report — "+rep.IP))      //nolint:errcheck
	fmt.Fprintf(w, "  generated:     %s\n", rep.GeneratedAt) //nolint:errcheck
	if rep.FirstSeen != "" {
		fmt.Fprintf(w, "  first seen:    %s\n", rep.FirstSeen) //nolint:errcheck
	}
	if rep.LastSeen != "" {
		fmt.Fprintf(w, "  last seen:     %s\n", rep.LastSeen) //nolint:errcheck
	}
	fmt.Fprintf(w, "  total strikes: %d\n", rep.TotalStrikes) //nolint:errcheck
	if rep.Country != "" {
		fmt.Fprintf(w, "  country:       %s\n", sanitizeField(rep.Country, reportFieldMax)) //nolint:errcheck
	}
	if rep.ASN != "" {
		fmt.Fprintf(w, "  network:       %s\n", formatASN(rep.ASN, rep.ASNOrg)) //nolint:errcheck
	}

	if rep.CurrentBan != nil {
		b := rep.CurrentBan
		fmt.Fprintln(w)                                      //nolint:errcheck
		fmt.Fprintln(w, s.header("Current ban"))             //nolint:errcheck
		fmt.Fprintf(w, "  banned at: %s\n", b.BannedAt)      //nolint:errcheck
		fmt.Fprintf(w, "  expires:   %s\n", expiryString(b)) //nolint:errcheck
		fmt.Fprintf(w, "  strike:    %d\n", b.Strike)        //nolint:errcheck
		if b.Reason != "" {
			fmt.Fprintf(w, "  reason:    %s\n", sanitizeField(b.Reason, reportReasonMax)) //nolint:errcheck
		}
	}

	if len(rep.Strikes) > 0 {
		fmt.Fprintln(w)                                            //nolint:errcheck
		fmt.Fprintln(w, s.header("Strike history (newest first)")) //nolint:errcheck
		for _, st := range rep.Strikes {
			fmt.Fprintf(w, "  [%d] %s  ttl %s  %s\n", //nolint:errcheck
				st.Strike, st.RecordedAt, ttlString(st.TTLSeconds),
				sanitizeField(st.Reason, reportReasonMax))
			for _, v := range st.Verdicts {
				fmt.Fprintf(w, "      %s\n", verdictString(v)) //nolint:errcheck
			}
		}
	}

	if len(rep.Actions) > 0 {
		fmt.Fprintln(w)                                     //nolint:errcheck
		fmt.Fprintln(w, s.header("Actions (newest first)")) //nolint:errcheck
		tw := tabwriter.NewWriter(w, 0, 0, 2, ' ', 0)
		for _, a := range rep.Actions {
			fmt.Fprintf(tw, "  %s\t%s\tstrike %d\tttl %s\t%s\n", //nolint:errcheck
				a.RecordedAt, sanitizeField(a.Op, reportFieldMax), a.Strike,
				ttlString(a.TTLSeconds), sanitizeField(a.Reason, reportReasonMax))
		}
		if err := tw.Flush(); err != nil {
			return err
		}
	}

	for _, ev := range rep.Evidence {
		fmt.Fprintln(w)                                                                    //nolint:errcheck
		fmt.Fprintln(w, s.header("Evidence — "+sanitizeField(ev.Source, reportReasonMax))) //nolint:errcheck
		if ev.Note != "" {
			fmt.Fprintf(w, "  note: %s\n", sanitizeField(ev.Note, reportReasonMax)) //nolint:errcheck
		}
		for _, line := range ev.Lines {
			fmt.Fprintf(w, "    %s\n", sanitizeField(line, reportLineMax)) //nolint:errcheck
		}
		if ev.Truncated {
			fmt.Fprintln(w, "  (excerpt truncated by size caps)") //nolint:errcheck
		}
	}
	return nil
}

// ── Markdown abuse report ────────────────────────────────────────────────────

// renderReportMarkdown builds a self-contained markdown document suitable to
// attach to an abuse complaint. All untrusted fields are sanitized and
// table-escaped; timestamps are the daemon's RFC 3339 UTC strings.
func renderReportMarkdown(rep sdk.AbuseReport, footer bool) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Abuse Report: %s\n\n", rep.IP)
	fmt.Fprintf(&b, "- **Generated:** %s\n", rep.GeneratedAt)
	fmt.Fprintf(&b, "- **Reported address:** %s\n", rep.IP)
	if rep.Country != "" {
		fmt.Fprintf(&b, "- **Country:** %s\n", mdCell(rep.Country, reportFieldMax))
	}
	if rep.ASN != "" {
		fmt.Fprintf(&b, "- **Network:** %s\n", mdCell(formatASN(rep.ASN, rep.ASNOrg), 2*reportFieldMax))
	}
	if rep.FirstSeen != "" {
		fmt.Fprintf(&b, "- **First observed:** %s\n", rep.FirstSeen)
	}
	if rep.LastSeen != "" {
		fmt.Fprintf(&b, "- **Last observed:** %s\n", rep.LastSeen)
	}
	fmt.Fprintf(&b, "- **Total strikes:** %d\n", rep.TotalStrikes)

	if rep.CurrentBan != nil {
		cb := rep.CurrentBan
		b.WriteString("\n## Current ban\n\n")
		b.WriteString("| Banned at | Expires | Strike | Reason |\n")
		b.WriteString("|---|---|---|---|\n")
		fmt.Fprintf(&b, "| %s | %s | %d | %s |\n",
			cb.BannedAt, expiryString(cb), cb.Strike, mdCell(cb.Reason, reportReasonMax))
	}

	if len(rep.Strikes) > 0 {
		b.WriteString("\n## Incident history (newest first)\n\n")
		b.WriteString("| Recorded at | Strike | Ban TTL | Reason | Detection |\n")
		b.WriteString("|---|---|---|---|---|\n")
		for _, st := range rep.Strikes {
			verdicts := make([]string, 0, len(st.Verdicts))
			for _, v := range st.Verdicts {
				verdicts = append(verdicts, verdictString(v))
			}
			fmt.Fprintf(&b, "| %s | %d | %s | %s | %s |\n",
				st.RecordedAt, st.Strike, ttlString(st.TTLSeconds),
				mdCell(st.Reason, reportReasonMax),
				mdCell(strings.Join(verdicts, "; "), 2*reportReasonMax))
		}
	}

	if len(rep.Actions) > 0 {
		b.WriteString("\n## Actions taken (newest first)\n\n")
		b.WriteString("| Recorded at | Action | Strike | TTL | Reason |\n")
		b.WriteString("|---|---|---|---|---|\n")
		for _, a := range rep.Actions {
			fmt.Fprintf(&b, "| %s | %s | %d | %s | %s |\n",
				a.RecordedAt, mdCell(a.Op, reportFieldMax), a.Strike,
				ttlString(a.TTLSeconds), mdCell(a.Reason, reportReasonMax))
		}
	}

	if len(rep.Evidence) > 0 {
		b.WriteString("\n## Evidence (log excerpts)\n")
		for _, ev := range rep.Evidence {
			fmt.Fprintf(&b, "\n### %s\n\n", mdCell(ev.Source, reportReasonMax))
			if ev.Note != "" {
				fmt.Fprintf(&b, "_%s_\n\n", mdCell(ev.Note, reportReasonMax))
			}
			// Indented code blocks (4 spaces), not fenced ones: a hostile log
			// line containing ``` can never terminate an indented block, so
			// evidence cannot inject markdown outside it.
			for _, line := range ev.Lines {
				fmt.Fprintf(&b, "    %s\n", sanitizeField(line, reportLineMax))
			}
			if ev.Truncated {
				b.WriteString("\n_(excerpt truncated by size caps)_\n")
			}
		}
	}

	if footer {
		b.WriteString("\n---\n\n_Generated by [EzyShield](https://github.com/evertramos/ezy-shield). All timestamps are UTC (RFC 3339)._\n")
	}
	return b.String()
}

// mdCell makes an untrusted string safe inside a markdown table cell:
// sanitizeField strips escape sequences, control characters (including
// newlines), and caps length; the remaining pipes are escaped so hostile
// reasons cannot break the table structure.
func mdCell(s string, max int) string {
	return strings.ReplaceAll(sanitizeField(s, max), "|", "\\|")
}

// ── Offender listing ─────────────────────────────────────────────────────────

func runReportList(cmd *cobra.Command, socketPath string, permanent bool, limit int) error {
	filter := ""
	if permanent {
		filter = "permanent"
	}
	resp, err := daemonRPC(context.Background(), socketPath,
		daemon.SocketRequest{Verb: "report", Filter: filter, Limit: limit})
	if err != nil {
		return err
	}

	var entries []daemon.ReportSummaryEntry
	if err := json.Unmarshal(resp.Data, &entries); err != nil {
		return fmt.Errorf("parse report list response: %w", err)
	}

	if jsonOutput {
		return writeJSON(cmd.OutOrStdout(), entries)
	}

	if len(entries) == 0 {
		msg := "no offenders recorded"
		if permanent {
			msg = "no permanently banned offenders"
		}
		_, err := fmt.Fprintln(cmd.OutOrStdout(), msg)
		return err
	}

	w := tabwriter.NewWriter(cmd.OutOrStdout(), 0, 0, 2, ' ', 0)
	fmt.Fprintln(w, "IP\tFIRST SEEN\tLAST SEEN\tSTRIKES\tBANNED\tCOUNTRY\tASN") //nolint:errcheck
	for _, e := range entries {
		fmt.Fprintf(w, "%s\t%s\t%s\t%d\t%s\t%s\t%s\n", //nolint:errcheck
			e.IP, e.FirstSeen, e.LastSeen, e.TotalStrikes,
			banState(e.Banned, e.Permanent),
			sanitizeField(e.Country, reportFieldMax),
			sanitizeField(e.ASN, reportFieldMax))
	}
	return w.Flush()
}

// banState renders the BANNED column: "permanent", "yes" (temporary), or "no".
func banState(banned, permanent bool) string {
	switch {
	case permanent:
		return "permanent"
	case banned:
		return "yes"
	default:
		return "no"
	}
}

// ── Shared formatting helpers ────────────────────────────────────────────────

// ttlString renders a ban duration in seconds; zero means permanent.
func ttlString(seconds int64) string {
	if seconds <= 0 {
		return "permanent"
	}
	return (time.Duration(seconds) * time.Second).String()
}

// expiryString renders the expiry of a ban ("permanent" when it never ends).
func expiryString(b *sdk.AbuseReportBan) string {
	if b.Permanent || b.ExpiresAt == "" {
		return "permanent"
	}
	return b.ExpiresAt
}

// formatASN joins "AS12345" and its organization into "AS12345 (Org)".
// Both values come from the GeoIP database — external data — so they are
// sanitized like any other untrusted field.
func formatASN(asn, org string) string {
	asn = sanitizeField(asn, reportFieldMax)
	if org == "" {
		return asn
	}
	return asn + " (" + sanitizeField(org, reportFieldMax) + ")"
}

// verdictString renders one detection verdict on a single line, e.g.
// "rules: ssh_bruteforce (score 92, confidence 0.90) — reason".
func verdictString(v sdk.AbuseReportVerdict) string {
	out := fmt.Sprintf("%s: %s (score %d, confidence %.2f)",
		sanitizeField(v.Source, reportFieldMax),
		sanitizeField(v.Category, reportFieldMax),
		v.Score, v.Confidence)
	if v.Reason != "" {
		out += " — " + sanitizeField(v.Reason, reportReasonMax)
	}
	return out
}
